---
services: docker

env:
  # Test source install on latest supported OSes.
  - distro: centos7
    playbook: test-source.yml
  - distro: fedora24
    playbook: test-source.yml

  # Test package install on all supported OSes.
  - distro: centos7
    playbook: test.yml
  - distro: centos6
    playbook: test.yml
  - distro: fedora24
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=true

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure Git is installed and at the right version.
  - 'docker exec --tty ${container_id} env TERM=xterm which git'
  - 'docker exec --tty ${container_id} env TERM=xterm test -x /usr/bin/git'
  - 'docker exec --tty ${container_id} env TERM=xterm git --version'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
