---
- name: install the latest version of git
  yum: name={{ item }} state=latest
  with_items:
    - git

- name: Clone vim config
  git:
    repo: "{{ vim_git_personal }}"
    dest: "{{ ci_homedir }}/.vim"
  become: yes
  become_user: "{{ ci_username }}"

- name: Link vim config
  file:
    src: "{{ ci_homedir }}/.vim/main.vim"
    dest: "{{ ci_homedir }}/.vimrc"
    owner: "{{ ci_username }}"
    group: "{{ ci_groupname }}"
    state: link

- name: Create vim autoload dir
  file:
    path: "{{ ci_homedir }}/.vim/autoload"
    state: directory
    mode: 0755
    owner: "{{ ci_username }}"
    group: "{{ ci_groupname }}"

- name: Create vim bundle dir
  file:
    path: "{{ ci_homedir }}/.vim/bundle"
    state: directory
    mode: 0755
    owner: "{{ ci_username }}"
    group: "{{ ci_groupname }}"

- name: "update local.vim file {{ ci_homedir }}/.vim/local.vim"
  template:
    src: local_vim.jinja2
    dest: "{{ ci_homedir }}/.vim/local.vim"
    owner: "{{ ci_username }}"
    group: "{{ ci_groupname }}"
    mode: 0644

- name: Install VIM bundles
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  become: yes
  become_user: "{{ ci_username }}"
  with_items: "{{ vim_git }}"

