---

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- debug:
    msg: "Username {{ vimconfig_username }}/{{ vimconfig_groupname }}"

- name: Clone vim config
  git:
    repo: "{{ vim_git_personal }}"
    dest: "{{ vimconfig_homedir }}/.vim"

- name: Link vim config
  file:
    src: "{{ vimconfig_homedir }}/.vim/main.vim"
    dest: "{{ vimconfig_homedir }}/.vimrc"
    owner: "{{ vimconfig_username }}"
    group: "{{ vimconfig_groupname }}"
    state: link

- name: Create vim autoload dir
  file:
    path: "{{ vimconfig_homedir }}/.vim/autoload"
    state: directory
    mode: 0755
    owner: "{{ vimconfig_username }}"
    group: "{{ vimconfig_groupname }}"

- name: Create vim bundle dir
  file:
    path: "{{ vimconfig_homedir }}/.vim/bundle"
    state: directory
    mode: 0755
    owner: "{{ vimconfig_username }}"
    group: "{{ vimconfig_groupname }}"

- name: "update local.vim file {{ vimconfig_homedir }}/.vim/local.vim"
  template:
    src: local_vim.jinja2
    dest: "{{ vimconfig_homedir }}/.vim/local.vim"
    owner: "{{ vimconfig_username }}"
    group: "{{ vimconfig_groupname }}"
    mode: 0644

- name: Install VIM bundles
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ vim_git }}"

